version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    network_mode: "host"
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
