version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate --noinput && uwsgi --ini /app/update/uwsgi.ini"
    volumes:
      - /tmp/uwsgi/:/tmp/uwsgi
      - /var/www/static:/static
      - /var/www/media:/media
      - /var/log/uwsgi:/var/log/uwsgi
    network_mode: "host"
    env_file: .env
    restart: always
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
