# Generated by Django 2.0.5 on 2018-05-21 10:41

import wagtail.core.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.core.fields.StreamField(
                (("slider_images", wagtail.images.blocks.ImageChooserBlock()),)
            ),
        ),
    ]
