# Generated by Django 2.0.5 on 2018-05-24 12:48

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_auto_20180523_1239"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="body",
            field=wagtail.core.fields.RichTextField(default=""),
            preserve_default=False,
        ),
    ]
