# Generated by Django 2.0.5 on 2018-05-25 08:53

import django.db.models.deletion
import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0019_delete_filter"),
        ("home", "0015_aboutpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicepage",
            old_name="header_image",
            new_name="cover_image",
        ),
        migrations.AddField(
            model_name="servicespage",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicespage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AlterField(
            model_name="servicepage",
            name="body",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
