# Generated by Django 2.0.5 on 2018-05-30 13:16

import wagtail.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0024_auto_20180527_0823"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="form_success_text",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
