# Generated by Django 2.0.9 on 2018-11-03 18:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0027_standardpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
