# Generated by Django 2.0.9 on 2018-12-07 10:34

import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_auto_20181207_1027"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="hover_content",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teampage",
            name="body_subtitle",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="teampage",
            name="body_title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
