# Generated by Django 2.0.9 on 2019-07-21 07:18

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0035_auto_20190719_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teampage',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='teampage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='hover_content',
        ),
        migrations.AlterField(
            model_name='teammember',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='home.AboutPage'),
        ),
        migrations.DeleteModel(
            name='TeamPage',
        ),
    ]
