# Generated by Django 2.0.9 on 2019-07-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_remove_servicepage_icon_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutpage",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="contacts",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="jobpostings",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="servicepage",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="servicespage",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="standardpage",
            name="cover_image",
        ),
    ]
