# Generated by Django 2.0.9 on 2020-09-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20200912_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='jobpostings',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
    ]
