# Generated by Django 2.0.9 on 2020-09-26 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_auto_20200912_1103"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS wagtailimages_image DROP COLUMN IF EXISTS file_hash;"
            "ALTER TABLE IF EXISTS wagtaildocs_document DROP COLUMN IF EXISTS file_hash;"
        )
    ]
