# Generated by Django 2.0.5 on 2018-05-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_auto_20180525_1654"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcategory",
            options={},
        ),
    ]
