# Generated by Django 2.0.5 on 2018-05-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_auto_20180525_1702"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectcategory",
            options={"ordering": ["sort_order"]},
        ),
    ]
