# Generated by Django 2.0.5 on 2018-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_auto_20180525_1713"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.AddField(
            model_name="project",
            name="categories",
            field=models.ManyToManyField(
                blank=True, null=True, to="portfolio.ProjectCategory"
            ),
        ),
    ]
