# Generated by Django 2.0.5 on 2018-05-25 17:26

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20180525_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='portfolio.ProjectCategory'),
        ),
    ]
