# Generated by Django 2.0.5 on 2018-05-26 14:09

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20180525_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=wagtail.core.fields.StreamField((('project_details', wagtail.core.blocks.StructBlock((('date', wagtail.core.blocks.CharBlock()), ('location', wagtail.core.blocks.CharBlock()), ('area_size', wagtail.core.blocks.CharBlock()), ('authors', wagtail.core.blocks.CharBlock()), ('status', wagtail.core.blocks.CharBlock())))), ('project_description', wagtail.core.blocks.StructBlock((('left_column', wagtail.core.blocks.RichTextBlock()), ('right_column', wagtail.core.blocks.RichTextBlock()))))), blank=True, null=True),
        ),
    ]
