# Generated by Django 2.0.5 on 2018-05-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20180526_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
