# Generated by Django 2.0.5 on 2018-06-06 11:52

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_auto_20180526_1425"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="portfolio.ProjectCategory"
            ),
        ),
    ]
