# Generated by Django 2.0.9 on 2019-07-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_projectimage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='size',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Full width'), (6, 'Half'), (4, 'One-third')], default=12),
        ),
    ]
