# Generated by Django 2.0.9 on 2019-07-21 07:30

import wagtail.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0013_auto_20190716_1351"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="subtitle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
