# Generated by Django 2.0.9 on 2019-07-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20190721_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioindex',
            name='cover_image',
        ),
    ]
