# Generated by Django 2.0.9 on 2019-07-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_portfolioindex_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='left_column',
        ),
        migrations.RemoveField(
            model_name='project',
            name='right_column',
        ),
    ]
