# Generated by Django 2.0.9 on 2020-09-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200912_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindex',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
    ]
