# Generated by Django 2.0.9 on 2020-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_portfolioindex_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindex',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description'),
        ),
        migrations.AddField(
            model_name='portfolioindex',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title'),
        ),
        migrations.AlterField(
            model_name='portfolioindex',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
    ]
