# Generated by Django 2.0.9 on 2020-09-12 10:56

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20200912_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioindex',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioindex',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='area_size_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='authors_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='search_description_en',
            field=models.TextField(blank=True, verbose_name='search description en'),
        ),
        migrations.AddField(
            model_name='project',
            name='seo_title_en',
            field=models.CharField(blank=True, help_text="Optional. 'Search Engine Friendly' title. This will appear at the top of the browser window.", max_length=255, verbose_name='page title en'),
        ),
        migrations.AddField(
            model_name='project',
            name='status_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title en'),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
