# Generated by Django 2.0.9 on 2020-09-12 11:03

from django.db import migrations


def copy_model_fields(apps, model_name, field_mapping):
    Model = apps.get_model("portfolio", model_name)
    for record in Model.objects.all():
        for key_to, key_from in field_mapping.items():
            setattr(record, key_to, getattr(record, key_from))
        record.save(update_fields=field_mapping.keys())


def copy_ru_to_en_fields(apps, schema_editor):
    copy_model_fields(
        apps,
        "PortfolioIndex",
        {
            "title_en": "title",
            "seo_title_en": "seo_title",
            "search_description_en": "search_description",
            "body_en": "body_ru",
            "subtitle_en": "subtitle_ru",
        },
    )
    copy_model_fields(
        apps, "ProjectCategory", {"name_en": "name_ru"},
    )
    copy_model_fields(
        apps,
        "Project",
        {
            "title_en": "title",
            "seo_title_en": "seo_title",
            "search_description_en": "search_description",
            "subtitle_en": "subtitle_ru",
            "location_en": "location_ru",
            "authors_en": "authors_ru",
            "status_en": "status_ru",
            "description_en": "description_ru",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0021_auto_20200912_1056"),
    ]

    operations = [migrations.RunPython(copy_ru_to_en_fields)]
