# Generated by Django 2.0.9 on 2020-11-22 13:42

from django.db import migrations


def create_new_menu_items(apps, schema_editor):
    MainMenuItem = apps.get_model("wagtailmenus", "MainMenuItem")
    CustomMainMenuItem = apps.get_model("menu", "CustomMainMenuItem")

    for existing_item in MainMenuItem.objects.all():
        new_item = CustomMainMenuItem()

        for field in MainMenuItem._meta.fields:
            value = getattr(existing_item, field.name)
            setattr(new_item, field.name, value)

        new_item.save()


def delete_new_menu_items(apps, schema_editor):
    CustomMainMenuItem = apps.get_model("menu", "CustomMainMenuItem")

    CustomMainMenuItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_new_menu_items, delete_new_menu_items),
    ]
